# A headless service to create DNS records. This is required for the inter-node communcation
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: kafka-source
  labels:
    app: kafka-source
spec:
  ports:
  - name: internal
    port: 9092
  - name: prometheus
    port: 5556
  clusterIP: None
  selector:
    app: kafka-source
