{
 "title": "Kafka Replication",
 "tags": [ "kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "query": "label_values(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\"}, topic)"
   },
   { "name": "cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kafka Broker Metrics",
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{topic=~\"${topic}\", name=~\"BytesInPerSec|BytesOutPerSec\"}) by (topic, name)",
     "legendFormat": "destination  {{topic}} {{name}}"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{topic=~\"${topic}\", name=~\"BytesInPerSec|BytesOutPerSec\"}) by (topic, name)",
     "legendFormat": "source  {{topic}} {{name}}"
    }
   ]
  },
  {
   "title": "Setup",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"kafka-mirror-tester-consumer-.+\", node!=\"\"})",
     "legendFormat": "cousumers"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"kafka-destination-.+\", node!=\"\"})",
     "legendFormat": "kafka brokers destination"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"ureplicator-worker-.+\", node!=\"\"})",
     "legendFormat": "ureplicator workers"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"kafka-source-.+\", node!=\"\"})",
     "legendFormat": "kafka brokers source"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"kafka-mirror-tester-producer-.+\", node!=\"\"})",
     "legendFormat": "producers"
    },
    {
     "expr": "avg(producer_number_of_topics * producer_number_of_partitions)",
     "legendFormat": "topicsXpartitions"
    }
   ]
  },
  {
   "title": "Producer and consumer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sum(rate(bytes_consumed[1m]))", "legendFormat": "bytes consumed / sec" },
    { "expr": "sum(rate(bytes_produced[1m]))", "legendFormat": "bytes produced / sec" }
   ]
  },
  {
   "title": "Message arrival latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(message_arrival_latency_ms{quantile=\"0.99\"})",
     "legendFormat": "latency max  quantile=\"0.99\""
    },
    {
     "expr": "avg(message_arrival_latency_ms{quantile=\"0.9\"})",
     "legendFormat": "latency avg quantile=\"0.9\""
    },
    {
     "expr": "avg(message_arrival_latency_ms{quantile=\"0.5\"})",
     "legendFormat": "latency avg quantile=\"0.5\""
    }
   ]
  },
  {
   "title": "Latency",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 13 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(message_arrival_latency_ms{quantile=\"0.9\"})",
     "legendFormat": "avg 90%ile"
    }
   ]
  },
  {
   "title": "in_order_message_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(in_order_message_count[1m]))",
     "legendFormat": "in_order_message_count {{pod}}"
    }
   ]
  },
  {
   "title": "Skipped or repeated messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(same_message_count[1m]))",
     "legendFormat": "same_message_count {{pod}}"
    },
    {
     "expr": "sum(deriv(old_message_count[1m]))",
     "legendFormat": "old_message_count {{pod}}"
    },
    {
     "expr": "sum(deriv(skipped_message_count[1m]))",
     "legendFormat": "skipped_message_count {{pod}}"
    }
   ]
  },
  { "title": "uReplicator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "uReplicator Metadata",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ureplicator_topic_observer{direction=\"destKafkaCluster\",metric=\"kafkaTopicsCounter\"}",
     "legendFormat": "Destination topics count"
    },
    {
     "expr": "ureplicator_topic_observer{direction=\"srcKafkaCluster\",metric=\"kafkaTopicsCounter\"}",
     "legendFormat": "Source topics count"
    }
   ]
  },
  {
   "title": "uReplicator Timing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(ureplicator_topic_observer{direction=\"srcKafkaCluster\",metric=\"refreshLatency\"})",
     "legendFormat": "Source refresh latency "
    },
    {
     "expr": "max(ureplicator_topic_observer{direction=\"destKafkaCluster\",metric=\"refreshLatency\"})",
     "legendFormat": "Destination refresh latency"
    },
    {
     "expr": "max(ureplicator_worker_rebalance)",
     "legendFormat": "Worker rebalance latency"
    }
   ]
  },
  {
   "title": "uReplicator errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ureplicator_topic_errors{component=\"controller\",metric_type=\"count\"}",
     "legendFormat": "topic errors"
    },
    {
     "expr": "ureplicator_topic_whitelist_manager{metric=\"numErrorTopics\"}",
     "legendFormat": "whitelist manager numErrorTopics"
    }
   ]
  },
  {
   "title": "uReplicator Pods Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"ureplicator-(worker|controller)-.+\"}) by (pod_name)",
     "legendFormat": "{{pod_name}} "
    }
   ]
  },
  {
   "title": "uReplicator Pods CPU Usage (cores)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"ureplicator-(worker|controller)-.+\"}[1m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Controller memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(java_lang_memory_heapmemoryusage_used{service=\"ureplicator-controller\"})",
     "legendFormat": "jvm heap memory usage"
    },
    {
     "expr": "avg(java_lang_memory_nonheapmemoryusage_used{service=\"ureplicator-controller\"})",
     "legendFormat": "jvm non heap memory usage"
    }
   ]
  },
  {
   "title": "Controller threads and FDs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(java_lang_operatingsystem_openfiledescriptorcount{service=\"ureplicator-controller\"})",
     "legendFormat": "open files"
    },
    {
     "expr": "avg(java_lang_threading_threadcount{service=\"ureplicator-controller\"})",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Workers memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used{service=\"ureplicator-worker\"}",
     "legendFormat": "jvm heap memory usage {{pod}}"
    },
    {
     "expr": "java_lang_memory_nonheapmemoryusage_used{service=\"ureplicator-worker\"}",
     "legendFormat": "jvm non heap memory usage {{pod}}"
    }
   ]
  },
  {
   "title": "Workers threads and FDs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_openfiledescriptorcount{service=\"ureplicator-worker\"}",
     "legendFormat": "open files {{pod}}"
    },
    {
     "expr": "java_lang_threading_threadcount{service=\"ureplicator-worker\"}",
     "legendFormat": "threads {{pod}}"
    }
   ]
  },
  {
   "title": "uReplicator filesystem usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{pod_name=~\"ureplicator-.+\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "uReplicator rebalance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(ureplicator_worker_rebalance)",
     "legendFormat": "rebalance time"
    }
   ]
  },
  {
   "title": "uReplicator Network bytes / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name=~\"ureplicator-.+\"}[5m])) by (container_name)",
     "legendFormat": "incoming"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod_name=~\"ureplicator-.+\"}[5m])) by (container_name)",
     "legendFormat": "outgoing"
    }
   ]
  },
  {
   "title": "${cluster} kafka cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka JVM Threads and FDs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(java_lang_threading_threadcount{pod=~\"kafka-.+\"})",
       "legendFormat": "max jvm threads {{pod}}"
      },
      {
       "expr": "avg(java_lang_threading_threadcount{pod=~\"kafka-.+\"})",
       "legendFormat": "avg jvm threads {{pod}}"
      },
      {
       "expr": "max(java_lang_operatingsystem_openfiledescriptorcount{pod=~\"kafka-.+\"})",
       "legendFormat": "max jvm FDs {{pod}}"
      },
      {
       "expr": "avg(java_lang_operatingsystem_openfiledescriptorcount{pod=~\"kafka-.+\"})",
       "legendFormat": "avg jvm FDs {{pod}}"
      }
     ]
    },
    {
     "title": "Kafka JVM memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(java_lang_memory_nonheapmemoryusage_used{pod=~\"kafka-.+\"})",
       "legendFormat": "max jvm non-heap {{pod}}"
      },
      {
       "expr": "avg(java_lang_memory_nonheapmemoryusage_used{pod=~\"kafka-.+\"})",
       "legendFormat": "avg jvm non-heap {{pod}}"
      },
      {
       "expr": "max(java_lang_memory_heapmemoryusage_used{pod=~\"kafka-.+\"})",
       "legendFormat": "max jvm heap {{pod}}"
      },
      {
       "expr": "avg(java_lang_memory_heapmemoryusage_used{pod=~\"kafka-.+\"})",
       "legendFormat": "avg jvm heap {{pod}}"
      }
     ]
    },
    {
     "title": "Kafka Pods Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{pod_name=~\"kafka-.+-.+\", container_name=\"broker\"}",
       "legendFormat": "{{container_name}} {{pod_name}} memory_usage"
      }
     ]
    },
    {
     "title": "Kafka Pods CPU Usage (cores)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{pod_name=~\"kafka-.+-[0-9]+\"}[1m])) by (container_name)",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "Kafka file system usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{pod_name=~\"kafka-.+\", container_name=\"broker\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "container_memory_failcnt",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_memory_failcnt{pod_name!=\"\"}[5m]) > 0",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Kafka partition and topic counts",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_controller_kafkacontroller_value{name=\"GlobalPartitionCount\",pod=~\"kafka-.+-.+\",service=\"broker\"}",
       "legendFormat": "{{name}} {{pod}}"
      },
      {
       "expr": "kafka_controller_kafkacontroller_value{name=\"GlobalTopicCount\",pod=~\"kafka-.+-.+\",service=\"broker\"}",
       "legendFormat": "{{name}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "${cluster} nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilisation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "node:node_cpu_utilisation:avg1m",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "CPU Saturation (Load1)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "node:node_cpu_saturation_load1:",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Disk IO Utilisation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "node:node_disk_utilisation:avg_irate",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Disk IO Saturation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "node:node_disk_saturation:avg_irate",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Net Utilisation (Transmitted)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "node:node_net_utilisation:sum_irate",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Net Saturation (Dropped)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "node:node_net_saturation:sum_irate",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Memory Utilisation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      { "expr": "node:node_memory_utilisation:", "legendFormat": "{{node}}" }
     ]
    },
    {
     "title": "Memory Saturation (Swap I/O)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "node:node_memory_swap_io_bytes:sum_rate",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}