kind: ConfigMap
metadata:
  name: jmx-config
  namespace: kafka-destination
apiVersion: v1
data:
  jmx-kafka-prometheus.yml: |+
    lowercaseOutputName: true
    jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:5555/jmxrmi
    ssl: false
    whitelistObjectNames: ["kafka.server:*","kafka.controller:*","java.lang:*"]
    rules:
      - pattern : kafka.server<type=ReplicaFetcherManager, name=MaxLag, clientId=(.+)><>Value
      - pattern : kafka.server<type=BrokerTopicMetrics, name=(BytesInPerSec|BytesOutPerSec|MessagesInPerSec), topic=(.+)><>OneMinuteRate
      - pattern : kafka.server<type=KafkaRequestHandlerPool, name=RequestHandlerAvgIdlePercent><>OneMinuteRate
      - pattern : kafka.server<type=Produce><>queue-size
      - pattern : kafka.server<type=ReplicaManager, name=(PartitionCount|UnderReplicatedPartitions)><>(Value|OneMinuteRate)
      - pattern : kafka.server<type=controller-channel-metrics, broker-id=(.+)><>(.*)
      - pattern : kafka.server<type=socket-server-metrics, networkProcessor=(.+)><>(.*)
      - pattern : kafka.server<type=Fetch><>queue-size
      - pattern : kafka.server<type=SessionExpireListener, name=(.+)><>OneMinuteRate
      - pattern : kafka.controller<type=KafkaController, name=(.+)><>Value
      - pattern : java.lang<type=OperatingSystem><>SystemCpuLoad
      - pattern : java.lang<type=Memory><HeapMemoryUsage>used
      - pattern : java.lang<type=OperatingSystem><>FreePhysicalMemorySize
      - pattern: 'java.lang<type=Threading><(.*)>ThreadCount: .*'
        name: java_lang_threading_threadcount
      - pattern: 'java.lang<type=OperatingSystem><.*>OpenFileDescriptorCount: .*'
        name: java_lang_operatingsystem_openfiledescriptorcount
      - pattern: 'java.lang<type=Memory><NonHeapMemoryUsage>(.+): .*'
        name: java_lang_memory_nonheapmemoryusage_$1

  jmx-zookeeper-prometheus.yaml: |+
    startDelaySeconds: 0
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:5555/jmxrmi
    ssl: false
    whitelistObjectNames: ["java.lang:*","org.apache.ZooKeeperService:*"]
    rules:
      - pattern: 'java.lang<type=Memory><HeapMemoryUsage>(.+): .*'
        name: java_lang_Memory_HeapMemoryUsage_$1
      - pattern: 'java.lang<type=Memory><NonHeapMemoryUsage>(.+): .*'
        name: java_lang_Memory_NonHeapMemoryUsage_$1
      - pattern: 'java.lang<type=OperatingSystem><.*>OpenFileDescriptorCount: .*'
        name: java_lang_OperatingSystem_OpenFileDescriptorCount
      - pattern: 'java.lang<type=OperatingSystem><.*>ProcessCpuLoad: .*'
        name: java_lang_OperatingSystem_ProcessCpuLoad
      - pattern: 'java.lang<type=Threading><(.*)>ThreadCount: .*'
        name: java_lang_Threading_ThreadCount
      # These are still incorrect, they need more work
      - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d)><>(\\w+)"
        name: "zookeeper_$2"
      - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d), name1=replica.(\\d)><>(\\w+)"
        name: "zookeeper_$3"
        labels:
          replicaId: "$2"
      - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d), name1=replica.(\\d), name2=(\\w+)><>(\\w+)"
        name: "zookeeper_$4"
        labels:
          replicaId: "$2"
          memberType: "$3"
      - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d), name1=replica.(\\d), name2=(\\w+), name3=(\\w+)><>(\\w+)"
        name: "zookeeper_$4_$5"
        labels:
          replicaId: "$2"
          memberType: "$3"
