apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka-destination
  labels:
    app: zookeeper
spec:
  ports:
  - port: 2181
    name: client
  - port: 5556
    name: prometheus
  selector:
    app: zookeeper
