apiVersion: v1
kind: ConfigMap
metadata:
  name: brooklin-jmx-prometheus-javaagent-config
  namespace: brooklin
data:
  jmx-prometheus-javaagent-config.yml: |+
    startDelaySeconds: 0
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    whitelistObjectNames:
        - "java.lang:*"
        - "metrics:*"
        - "kafka.consumer:*"
        - "kafka.producer:*"
