apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-mirror-tester-consumer
  labels:
    app: kafka-mirror-tester-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-mirror-tester-consumer
  template:
    metadata:
      labels:
        app: kafka-mirror-tester-consumer
    spec:
      containers:
      - name: consumer
        image: rantav/kafka-mirror-tester:latest
        args:
        - consume
        - --bootstrap-servers
        - 18.207.184.105:9093
        - --consumer-group
        - group-1
        - --topics
        - topic101,topic102,topic103,topic104
        - --num-partitions
        - "1"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - kafka-destination
            namespaces:
            - kafka-destination
            topologyKey: "kubernetes.io/hostname"
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ureplicator
              - key: component
                operator: In
                values:
                - worker
            namespaces:
            - ureplicator
            topologyKey: "kubernetes.io/hostname"